### PR TITLE
Adds support for resource identifier other than :id

### PR DESCRIPTION
**Pull request by sthaha**
Previously all Spyke resources must be identified by :id, which
makes it hard to create a generic response middleware that can
handle different identifier per resource.

This patch allows resource identifier to be declared using `id_key`
class method and defaults to :id

Ref: https://github.com/balvig/spyke/issues/69

### CODE REVIEW

**Comment by balvig** [comment]
Hey there @sthaha thanks for this! 

Fleshed out the specs a bit and noticed one edge case.

When passing in `nested_attributes`, I guess client side we're abstracting away the actual name of the primary key, and should still be passing in `:id` instead?

Specs here: https://github.com/balvig/spyke/commit/93bb2806827bffd5dfa7e10083a6caf40b99dbfc

**Comment by sthaha** [comment]
@balvig thanks for fleshing out the spec, I wasn't quite happy with the test I wrote but thought it was good enough to kickstart a discussion.

I was thinking about the current implementation, currently for Spyke subclass (not sure what a good name is - SpykeRecord?), it is allowed to declare a `primary_key|id_key` and that attribute is accessible using `#id` method as well as the `#<primary_key>`; 
e.g: `User.all.first.id` is the same as `User.all.first.user_id` (missing spec?)

I am not sure what should be done in the case there is an attribute called `:id` but isn't the `primary_key`.  For example:
```json
{ "name":"Joe", "id":555, "pk_id":12345 }
```
where `pk_id` is the primary key.

Similar discussion on [SF about ActiveRecord](https://stackoverflow.com/questions/23298349/rails-activerecord-handle-an-id-column-that-is-not-the-primary-key)


@balvig To answer the original question, keeping aside the edge case above, shouldn't both `:id` and `:custom_primary_key` be an acceptable input to create a SpykeRecord as the current implementation understands that the method `#id` is the same as `#custom_primary_key` thus both `:id` and `:custom_primary_key`  are acceptable.

On a different note do you think `primary_key` instead of `id_key` is better?

**Comment by balvig** [comment]
The way I think about it is that Spyke basically treats API endpoints as a form of database, and that you should be able to use `form_for`, `simple_form_for` etc like you would with an ActiveRecord object. I _think_ nested forms will default to use a hidden field named `:id` regardless of what the field is named in the database, so probably makes sense to mimick this behavior?

Just realizing now that the tricky part might be to ensure that these fields are still sent _back_ to the API using the _custom_name, probably we're missing a test for that too! :sweat_smile:

**Comment by sthaha** [comment]
```ruby
    def test_custom_primary_key_on_find
      endpoint = stub_request(:get, 'http://sushi.com/users').to_return_json(result: [{ user_id: 1 }])
      users = User.all.to_a
      assert_requested endpoint
      assert_equal 1, users.first.id
      assert_equal 1, users.first.user_id
    end

    def test_custom_primary_key_and_id_are_the_same
      endpoint = stub_request(:get, 'http://sushi.com/users').to_return_json(result: [{ user_id: 1 }])
      user = User.all.to_a.first
      assert_requested endpoint
      assert_equal 1, user.id
      assert_equal user.user_id, user.id
    end

    def test_custom_primary_key_but_has_id_attribute
      endpoint = stub_request(:get, 'http://sushi.com/users').to_return_json(
          result: [{ user_id: 1, id: 42 }])
      user = User.all.to_a.first
      assert_requested endpoint
      assert_equal 42, user.id
      assert_equal 1, user.user_id   # skip fails -> returns 42 :(
    end
```
@balvig For the above, while the first two passes, the last one fails

**Comment by sthaha** [comment]
@balvig any suggestion for a better way to submit my changes to the spec branch other than pasting it here?

**Comment by balvig** [comment]
Is that edge case something that's happening in your current project? Maybe just getting the basics working for now is okay :smile:  (how does ActiveRecord handle this?)

**Comment by sthaha** [comment]
@balvig no, I haven't encountered the edge in my usage so far but it did cross my mind after submitting the patch. Either way like activerecord it will be useful to allow access to `@attribute` using `Sypke#[:attribute_name]` method. And can be added later if not already present.

I am curious about the odd test result thou. it seems `:id` takes preference over explicitly declared `id_key`
```ruby
   def test_custom_primary_key_but_has_id_attribute
      endpoint = stub_request(:get, 'http://sushi.com/users').to_return_json(
          result: [{ user_id: 1, id: 42 }])
      user = User.all.to_a.first
      assert_requested endpoint
      assert_equal 42, user.id    # must 
      assert_equal 1, user.user_id   # skip fails -> returns 42 :(
    end
```

**Comment by sthaha** [comment]
@balvig I have added few more tests and _hopefully_ fixed the conflict between `:id` and `:primary_key`. I have also renamed the `id_key` to `primary_key` as it maps closely to `ActiveRecord`.

**Comment by sthaha** [comment]
@balvig Would be great if you could review the latest PR ( d868544 ) . Happy to fix any blockers.

**Comment by balvig** [comment]
Thanks @sthaha I'll get to it shortly! Bit swamped this week, thanks again 😄

**Comment by balvig** [comment]
Fixed in https://github.com/balvig/spyke/commit/ea0969e3bb7e25acc131e5f1a89114d0ef4087a4

**Comment by sthaha** [comment]
@balvig thank you :-)   you rock!

**Pull request closed without merging**
