### PR TITLE
Tackling issue #10 and supporting APIs with extension

### PR DESCRIPTION
**Pull request by chriso0710**
This is my suggested change to support #10 

- switched from uri_template to addressable
- compatible with uri_template colon format (although I am not entirely happy with the gsub regex, maybe someone finds a better/shorter regex for converting to addressable RFC)
- all tests are passing, added some more for Path
- added some (hopefully) helpful information and code fragments for working with XML APIs to the README

### CODE REVIEW

**Comment by balvig** [comment]
Thanks a lot for the contribution @chriso0710!! 🙇 
Let me try and take a look at this today or tomorrow and get it wrapped up 👍

**Comment by balvig** [comment]
(could you check the "allow owner to make changes" checkbox? 🙏 )

**Comment by chriso0710** [comment]
Looking forward to it.
The "Allow edits from maintainers" was checked already.

**Comment by balvig** [comment]
@chriso0710 made a couple of tweaks above! 

Although I appreciate the extra docs, I think for now showing just the JSON version as an example is hopefully sufficient, I've tried to change the wording in the existing docs a bit to clarify that Spyke isn't necessarily just for JSON. Hope that makes sense 🙏 

If possibly, do you think you could try out this branch with your project for a while, to see how it goes before merging to master?

Once again thanks for your contribution, checking off one of the items on the checklist! 👍

**Comment by chriso0710** [comment]
Thanks for your comments and tweaks!

IMHO extracting the converter into it's own class could be seen as somewhat "overengineered". But I can surely live with that ;-)
I understand your arguments for dropping the XML parser code example, but I would love to see some (tiny) examples for working with extensions or other response formats in the docs.

I will pull the changes and use this branch for my XML API project. Will keep you posted.

Christian

**Comment by balvig** [comment]
> IMHO extracting the converter into it's own class could be seen as somewhat "overengineered". But I can surely live with that ;-)

Heh, just to explain: When looking at the diff I was basically having difficulty grokking the regex (my arch nemesis 😅 ), and so I felt the inclination to be able to comment their purpose using _method names_ instead of having `# comments`, as the latter tend to go out of date more often than the former 😉 .

Thanks again @chriso0710! 🙏

**Comment by chriso0710** [comment]
I have been testing in full detail for the last 7 days against most of the easyredmine XML API endpoints (http://docs.easyredmine.apiary.io/#)

Everything works great. I had not a single problem with the new branch, as expected :-)

**Comment by balvig** [comment]
@chriso0710 awesome, that's great to hear! 
I will try this out in a bit more detail as well, and then look to merging/releasing.

Thanks again!

**Comment by balvig** [comment]
Released as [5.1.0](https://rubygems.org/gems/spyke/versions/5.1.0), thanks again @chriso0710! 🙏

**Comment by chriso0710** [comment]
Fantastic. 
Thank you for your time and effort working on Spyke.

**Pull request merged**
