### PR TITLE
Allow uri to be inherited

### LINKED ISSUE #18: Define uri in base class and extend it from sub-classes
Hi,

I defined a base class to handle my models like so:

```ruby
module Models
  class Base < Spyke::Base
  end
end
```

and then inherits from it in my models:

```ruby
module Models
  class Content < ::Models::Base
  end
end
```

All my models will follow the same `uri` schema (ex: `uri "/api/v1/constants/(:name)"`). Is it possible to define the base uri schema in the parent class?

```ruby
module Models
  class Base < Spyke::Base
    uri '/api/v1/'
  end
end
```

and then extend it in each sub-classes.

### PR DESCRIPTION
**Pull request by balvig**
Closes #18
Previously inheriting from other Spyke::Base classes would ignore the uri of those superclasses, ie:

```ruby
class Post < Spyke::Base
  uri "postings/(:id)"
end

class SpecialPost < Post
end

Post.find(1) # => GET /postings/1
SpecialPost.find(1) #=> GET /special_posts/1
```

This fixes it so that uri is inherited:

```ruby
Post.find(1) # => GET /postings/1
SpecialPost.find(1) #=> GET /postings/1
```

### CODE REVIEW

**Comment by gottfrois** [comment]
Hey, thanks for the work.

Thinking about this, I think inheriting is not enough. We should allow to define a base uri in parent class and use it to prepend uri defined in the sub-classes:

```ruby
class Base < Spyke::Base
  uri 'http://foo.com/api/v1/'
end

class Post < Base
  uri '/posts/(:id)'
end

Post.find(1) # => GET http://foo.com/api/v1/posts/1
```

This is possible using the URI module like so:

```ruby
require 'uri'

URI.join('http://foo.com/api/v1/', 'posts/(:id)').to_s
 => "http://foo.com/api/v1/posts/(:id)"
```

**Comment by balvig** [comment]
The domain of the API is defined in Faraday when configuring the connection:

```ruby
Spyke::Config.connection = Faraday.new(url: 'http://api.com') do |c|
...
end
```

...so `uri` is really only intended for configuring the path of each resource within that domain :smile: 

As for "prepending", although I can see it might be convenient (especially for sites with versioning), I think I might be surprised by that behavior when inheriting from a base class. I wouldn't expect the `uri` I see defined in a class to be affected by other classes, so somehow I think it's better to be explicit in this case! :sweat: 

Would be nice if this could be done in Faraday itself, ie 

```ruby
Faraday.new(url: 'http://api.com/v2/')
```

... but seems like it cuts off the path :disappointed: 

In any case thanks for the suggestion! :wink:

**Comment by gottfrois** [comment]
What about a `base_uri` we could define in the parent class ? Sub-classes would still define `uri` like usual but it would prefix with `base_uri` if present.

```ruby
class Base < Spyke::Base
  base_uri '/api/v1/'
end

class Post < Base
  uri '/posts/(:id)'
end
```

**Comment by balvig** [comment]
Hehe, really to me feels like it's something that should be set when configuring the API connection - ideally I'd like to be able to just do this:

```ruby
Spyke::Config.connection = Faraday.new(url: 'http://api.com/api/v1')
```

I dunno if it's possible in Faraday (maybe you can dig around? :sweat_smile:), but I'd like to avoid adding more methods to Spyke::Base to cover it! :smile:

**Comment by gottfrois** [comment]
Yep true, i was suprised first when i saw it would not work on faraday :( I'll digg a little more

**Comment by balvig** [comment]
@gottfrois check out #25 - maybe this takes care of your use case? :smile:

**Comment by gottfrois** [comment]
Yep works great!

```ruby
::Spyke::Config.connection = ::Faraday.new(url: URI.join('http://foo.com/', "api/v#{api_version}/")) do |c|
```

and in my models

```ruby
uri 'constants/(:name)'
```

Thx :)

**Comment by balvig** [comment]
Hurray! And thanks to @jontebol for discovering the cause of this :+1:

**Comment by jontebol** [comment]
:+1:

**Pull request merged**
