### PR TITLE
Remove Ruby/Rails warnings

### PR DESCRIPTION
**Pull request by nickcampbell18**
Just a couple of quick fixes, I noticed this while doing a Rails upgrade.

### CODE REVIEW

**Comment by nickcampbell18** [comment]
CI is broken presumably because it's running the tests on my repo, not the primary one:

```
/home/circleci/.nvm/versions/node/v10.0.0/lib/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

Exited with code exit status 1
```

But all of the actual tests pass at least 😄

**Comment by balvig** [comment]
Awesome, thanks a lot @nickcampbell18! 

I noticed you had [a different approach originally](https://github.com/balvig/spyke/commit/c032c94e750e1e2d624d1678c282ee34e0c10acb), the one that the deprecation warning mentions, did you run into difficulties with that one?

**Comment by nickcampbell18** [comment]
Yes - I added it to the commit message, I'll paste it here for clarity:

> Unfortunately, `thread_mattr_accessor` was only introduced in Rails 5,
and the behaviour significantly changed in Rails 6, so it isn't a stable
replacement API. Instead, we can just use a thread-local variable, which
is how Rails itself does it:
https://github.com/rails/rails/blob/6a8c51b19b6a20511b26d486419ccaebbca93419/activesupport/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb

We've got this problem simply because we're trying to support as many Rails versions as possible, but that proposed API wasn't that stable in older versions. I've switched to some Ancient Ruby™️ which shouldn't break for anybody!

**Comment by balvig** [comment]
@nickcampbell18 ah gotcha, thanks for explaining!

I was actually earlier looking at https://github.com/rails/rails/blob/6a8c51b19b6a20511b26d486419ccaebbca93419/activesupport/lib/active_support/isolated_execution_state.rb#L6 which seems to support both threads and fibers and wondering if it might be preferable to lean on that (although it does mean another dependency on some "private API") to allow that support.

I was putting something together in #128, but haven't yet gotten around to testing it properly.

(As you can see, I've also copped out a bit and simply checked for Rails versions 😅 , which I think is also acceptable in moderation, as we can clearly see when a branch can be deleted and we have the coverage across versions.)

**Comment by nickcampbell18** [comment]
Also a good fix 😄 feel free to pick & choose anything from this PR, I just thought I'd offer some small things I noticed while testing!

**Comment by balvig** [comment]
Thanks once again @nickcampbell18! 

I've already committed https://github.com/balvig/spyke/commit/c446ecfee749a3f90956e5d8ca4c8c823bfa89a3, and will give the different registry implementations a test sometime soon 👌

**Comment by balvig** [comment]
This was addressed in #128. Thank you @nickcampbell18! 👍

**Pull request closed without merging**
